[package]
name = "m5tui-device"
version = "1.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false
description = "ESP32-S3 / M5GFX device render target for m5Tui."

[lints]
workspace = true

[dependencies]
m5tui-core = { path = "../m5tui-core" }
m5tui-themes = { path = "../m5tui-themes" }
